### ISSUE TITLE
Compose project gives error for escaping $ for mongo replica set even though it already is?

### ISSUE THREAD

**Issue by jrj2211** [docker/dev-environments#117]
**Describe the bug**
I'm trying to use a mongo replica set in my dev environment. This typically is done by using the healthcheck to run the "rs.initiate()" command for mongo. When running docker-compose up manually it works fine, but when run through dev-enviroments I get an error about escaping a $.

My docker-compose.yaml is this:

```
version: "3.7"
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_DATABASE: zyphox
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s

volumes:
  mongo-data:
```

When running this as a dev-enviroment though I'm getting the error:

```
invalid interpolation format for services.mongodb.healthcheck.test.[]: "test $(echo \"rs.initiate().ok || rs.status().ok\" | mongo --quiet) -eq 1". You may need to escape any $ with another $
exit status 15
```

It already has two $. I've tried adding another and removing one.

**To Reproduce**
1. Create a docker compose project using the docker-compose.yaml file above
2. In Docker Desktop application, create a Dev environment using the local project
3. During setup it will error with exist status 15

**Expected behavior**
It is already escaped and should run as if "docker-compose up" was called

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19044.1706

**Version of Docker Desktop:**  
You can find the version by clicking on the `About Docker Desktop` menu
```
Docker Desktop 4.9.0 (80466)
```

**Additional context**
