### ISSUE TITLE
Option to start dev environments created from git source inside a WSL context

### ISSUE THREAD

**Issue by Mario1159** [docker/dev-environments#143]
### **Tell us about your request**

**Context**
Starting containers inside a WSL distribution is useful for running X/Wayland graphical applications with the WSL graphics stack ([wslg](https://github.com/microsoft/wslg)).
When starting dev environments using Docker Desktop from a git source, containers are started from a normal windows path outside WSL (_Users/user/.docker/devenvironments/_), this means the container wont have access to the WSLg system distribution, thus the environment variables and paths binded to enable graphics wont exist or make sense.

**Request**
Having an option to start the container in the default WSL distribution when creating the dev environment by git source or have some kind of integration with the [WSLg container binds](https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md).

**Motivation**
This would facilitate windows developers using dev enviroments that also provide tool stacks with graphical applications.

---

### **Are you currently working around the issue?**
Graphical applications can be executed in Windows from a docker-compose.yml/compose-dev.yaml file that resides in a WSL distribution with the 'Local directory' option.
A docker compose environment example that enable graphics in Windows:
```yml
services:
  devenv:
    image: ubuntu:latest
    command: sleep infinity
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
```
