### ISSUE TITLE
dev-environments 

### ISSUE THREAD

**Issue by finnweiler** [docker/dev-environments#80]
**Describe the bug**
I receive an error with exit status 17 when setting up a dev environment for my docker-compose project.
When disabling the "Use Docker Compose V2", the setup works, however then I don't have Git installed in my dev-container! Using the dev-envs without docker-compose works just fine.

**To Reproduce**
I am using the following configuration: 
Then I create my dev-env by entering my clone url. 

`.docker/docker-compose.yaml`:
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wortwert
      - MYSQL_ROOT_PASSWORD=dev
    ports:
      - "3306:3306"
volumes:
  db-data:
```

`Dockerfile`:
```
FROM alpine:3.14 AS build
WORKDIR /github.com/finnweiler/wortwert-software
COPY . .

RUN apk add --update nodejs npm

WORKDIR /github.com/finnweiler/xxx/frontend
RUN npm install

WORKDIR /github.com/finnweiler/xxx/backend
RUN npm install

FROM build AS development

CMD [ "top" ]
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28830219/145708414-71fbdde2-15bd-4a1c-a557-42c7855671af.png)

**Desktop (please complete the following information):**
 - OS: **Windows 11 Pro**
 - Version: 21H2

**Version of Docker Desktop:**  
You can find the version by clicking on the `About Docker Desktop` menu
```
Docker Desktop 4.3.1 (72247)
```
